#!/usr/bin/env python3
"""llm-wiki: a live model of an environment plus the accumulated reasoning
over it, stored as plain files. Three layers: `sources/` (immutable),
`wiki/` (the model owns it), `SCHEMA.md` (the configuration that matters).

`add --url` depends on readability-lxml and lxml, declared in
pyproject.toml. See docs/design/llm-wiki.md for the full design.
"""
from __future__ import annotations

import argparse
import hashlib
import ipaddress
import os
import re
import shutil
import socket
import subprocess
import sys
import tempfile
import unicodedata
import urllib.error
import urllib.parse
import urllib.request
from datetime import datetime, timezone
from http.client import HTTPResponse
from pathlib import Path
from typing import NamedTuple

TIMESTAMP_FORMAT = "%Y-%m-%dT%H:%M:%SZ"
PAGE_FIELDS = ("title", "summary", "category", "updated")
GLOBAL_STORE_NAME = "agent-kb"
MAX_SLUG_LEN = 120
SLUG_HASH_LEN = 12  # hex chars of fallback hash when a title strips to nothing
ALLOWED_URL_SCHEMES = ("http", "https")
ALLOWED_CONTENT_TYPES = ("text/html", "application/xhtml+xml")
MAX_FETCH_BYTES = 5_000_000  # single-page cap; a runaway body errors, not streams forever
MAX_REDIRECTS = 5
RG_OK_CODES = (0, 1)  # 0 = match, 1 = no match; anything else is a real error

INDEX_BANNER = (
    "<!-- GENERATED by llm-wiki. Do not hand-edit; edit the page instead, "
    "`add`/`page` regenerate this file automatically. Repair-only: "
    "`llm-wiki index`. -->"
)

SCHEMA_TEMPLATE = '''# SCHEMA

This file is the configuration that matters. It tells an agent working in
this kb what the layers mean, how to name and link pages, what frontmatter
every file carries, when to write a new page versus extend one that
exists, which retrieval path costs the fewest tokens for a given question,
and the concrete commands for the ingest, query and lint workflows.

## What this is

A kb is a live model of an environment plus the accumulated reasoning over
it, stored as plain files an agent can read without asking permission.
Three layers.

| Layer | Rule |
|---|---|
| `sources/` | Immutable. Articles, papers, snapshots. Written once, never edited, never deleted. The source of truth. |
| `wiki/` | The model owns it. Pages it writes and keeps updating as new sources land. Read this layer, and write it. |
| `SCHEMA.md` | This file. Conventions and workflows, co-evolved by hand as the kb grows. |

## Verbs

    llm-wiki init [PATH]     create the kb tree, default ./.kb
    llm-wiki where           print which kb resolves, and how
    llm-wiki add TITLE       write a source, body from stdin, or --url to fetch one
    llm-wiki page TITLE      write or update a wiki page, body from stdin, or --touch to re-stamp only
    llm-wiki index           repair-only: regenerate wiki/index.md (add/page do this already)
    llm-wiki log KIND TITLE  repair-only: append one entry to log.md (add/page do this already)
    llm-wiki links PAGE      print pages that link to PAGE

`add` and `page` are the only write paths. Both append a log.md entry and
regenerate wiki/index.md themselves after a successful write, so the two
files never drift from what is on disk.

## Page naming

- Filenames are kebab-case: `widget-catalog.md`, not `WidgetCatalog.md` or
  `widget_catalog.md`.
- A `[[wikilink]]` targets the filename without the `.md` extension:
  `[[widget-catalog]]` points at `wiki/widget-catalog.md`.

## Frontmatter contracts

Scalars only. No nested values, no lists.

Source frontmatter (files under `sources/`):

- `origin` one of `curated`, `research`, `collector`
- `source` a URL or other reference, may be empty
- `collected_at` ISO 8601 UTC timestamp

For a collector snapshot, additionally:

- `job` the collector job name
- `mode` `full` or `partial`

`llm-wiki add` never writes `job` or `mode`. Collector snapshots are
written by the collector itself, which does not exist yet.

Page frontmatter (files under `wiki/`):

- `title`
- `summary`
- `category`
- `updated`

`wiki/index.md` is built from exactly those four page fields and nothing
else. It is generated. Never hand-edit it.

## New page or extend an existing one

Pages are updated, not regenerated. A page accumulates reasoning that
exists nowhere else, so:

- A question already answered on some page: run `llm-wiki page TITLE`
  again with the new body; it replaces the body and keeps whatever
  frontmatter fields were not passed as a flag.
- A genuinely new topic with no page to extend: `llm-wiki page TITLE` with
  no existing file creates one.
- Never regenerate a page from sources. A source is read once and folded
  in; the page keeps whatever reasoning was already written onto it.
  `page` always reads a real body from stdin; to re-stamp `updated`
  without touching the body, pass `--touch`. Stdin is still read, but
  `--touch` refuses a non-empty one (piped, redirected, any size)
  instead of guessing which one the caller meant.

## Retrieval, largest saving first

1. A previously answered question is a page, not a search. One
   synthesized page costs 500 to 1,500 tokens. Re-deriving the same
   answer from three sources costs 20,000 or more. File the answer back
   onto a page; that is the only step here that gets cheaper the more
   the kb is used.
2. Read `wiki/index.md` before searching anything. At a few hundred
   pages the whole index costs roughly 5,000 tokens, cheaper than one
   wrong guess at what to search for.
3. Freshness comes from the index's `updated` column, not from opening
   the page. If an agent has to open a page to learn it is stale, full
   price was already paid to discard it.
4. This file is what makes the cheap path get taken. None of the above
   happens unless it is written down.

Route by question shape, in this order:

1. Check `wiki/index.md` for an existing page.
2. Read that page if one matches.
3. Check what links to it: `rg -l '\\[\\[page-name\\]\\]'` or
   `llm-wiki links PAGE`.
4. Nothing answers it yet: search `sources/` directly.
5. File what was found back onto a page; `page` regenerates the index.

## No search verb

There is no search command. `rg` (or `grep`) is the query engine.

Backlinks: given a page, find what else touches it.

    rg -l '\\[\\[page-name\\]\\]'

## Workflows

The paths below are relative to the kb root. cd there first:

    cd "$(llm-wiki where | head -1)"

Ingest a source, body from stdin:

    llm-wiki add "Title of the thing" --origin curated \\
        --source "https://example.com" <<'EOF'
    body text goes here
    EOF

Ingest a source, fetched from a URL (needs readability-lxml and lxml):

    llm-wiki add --url "https://example.com/article"

Query before writing anything:

    rg -l "search term" wiki/
    rg -l "search term" sources/

Read the index first for an overview:

    cat wiki/index.md

Follow a backlink chain:

    rg -l '\\[\\[page-name\\]\\]' wiki/
    llm-wiki links page-name

Write or update a page, body from stdin:

    llm-wiki page "Widget Catalog" --summary "one line" --category ref <<'EOF'
    page body goes here
    EOF

Re-stamp a page's `updated` timestamp without touching its body (stdin
must be empty; a real body on stdin, piped or redirected, is refused):

    llm-wiki page "Widget Catalog" --touch

Repair the index or log by hand only if they ever drift, which `add` and
`page` are meant to prevent:

    llm-wiki index
    llm-wiki log query "short description"
    llm-wiki log lint "short description"

Lint pass, read the last few log entries:

    grep "^## \\[" log.md | tail -5
'''


class ResolvedKb(NamedTuple):
    """A kb path plus how it was found, for `where` to report."""

    path: Path
    how: str


def flatten(text: str) -> str:
    """Collapse embedded control characters (newlines, carriage returns,
    tabs, ...) to spaces, so a value never breaks a one-line record
    (frontmatter field, log entry, index cell)."""
    return re.sub(r"[\x00-\x1f\x7f]", " ", text)


def parse_frontmatter(text: str) -> tuple[dict[str, str], str]:
    """Split scalar frontmatter off `text`.

    Returns `({}, text)` unchanged if `text` carries no exact `---`
    terminator line, so a page missing or malformed frontmatter degrades
    instead of raising or swallowing body content.
    """
    if not text.startswith("---\n"):
        return {}, text
    lines = text.split("\n")
    end = None
    for index, line in enumerate(lines[1:], start=1):
        if line == "---":
            end = index
            break
    if end is None:
        return {}, text
    fields: dict[str, str] = {}
    for line in lines[1:end]:
        if not line.strip() or ":" not in line:
            continue
        key, _, value = line.partition(":")
        value = value.strip()
        if len(value) >= 2 and value[0] == '"' and value[-1] == '"':
            value = value[1:-1]
        fields[key.strip()] = value
    # render_frontmatter's caller always inserts exactly one blank line
    # between the closing `---` and the body; strip exactly that one line,
    # not every leading newline, so a body that itself starts with blank
    # lines round-trips byte for byte.
    body_lines = lines[end + 1 :]
    if body_lines and body_lines[0] == "":
        body_lines = body_lines[1:]
    body = "\n".join(body_lines)
    return fields, body


def render_frontmatter(fields: dict[str, str]) -> str:
    """Render `fields` as a scalar-only `---` block, one double-quoted
    `key: "value"` per line. Quoting keeps an empty value round-trippable
    (`key: ""`, not a dangling trailing space) and matches what
    `parse_frontmatter` strips back off on read."""
    lines = ["---"]
    for key, value in fields.items():
        lines.append(f'{key}: "{flatten(str(value))}"')
    lines.append("---")
    return "\n".join(lines) + "\n"


def slugify(title: str) -> str:
    """Kebab-case a title for use as a filename, ASCII-normalized and
    length-capped so a long or accented title stays a valid path. A title
    that normalizes to nothing ASCII (most non-Latin scripts) falls back
    to a hash of the original title, so distinct titles never collapse
    onto the same slug."""
    normalized = unicodedata.normalize("NFKD", title)
    slug = re.sub(r"[^a-z0-9]+", "-", normalized.lower()).strip("-")
    slug = slug[:MAX_SLUG_LEN].strip("-")
    if slug:
        return slug
    digest = hashlib.sha1(title.encode("utf-8")).hexdigest()[:SLUG_HASH_LEN]
    return f"untitled-{digest}"


def _normalize_title_for_compare(title: str) -> str:
    """Fold a title down for the "is this the same page" check: NFC so
    NFD/NFC accented spellings match, casefold so casing doesn't matter,
    and whitespace collapsed and trimmed so doubled or leading/trailing
    spaces don't matter. Never truncated: `slugify` caps filenames at
    `MAX_SLUG_LEN`, so two different titles can share a slug while still
    differing beyond that length. Comparing the full title is what turns
    that case into a loud collision instead of a silent body merge."""
    normalized = unicodedata.normalize("NFC", flatten(title))
    return re.sub(r"\s+", " ", normalized).strip().casefold()


def utc_timestamp() -> str:
    """ISO 8601 UTC timestamp, second precision."""
    return datetime.now(timezone.utc).strftime(TIMESTAMP_FORMAT)


def global_kb_root() -> Path:
    """The global fallback store, honouring XDG_DATA_HOME."""
    xdg_data_home = os.environ.get("XDG_DATA_HOME")
    base = Path(xdg_data_home) if xdg_data_home else Path.home() / ".local" / "share"
    return base / GLOBAL_STORE_NAME


def resolve_kb(explicit: str | None) -> ResolvedKb:
    """Find the kb in play: `--kb` override, else walk up from cwd for a
    `.kb` directory, else the global store."""
    if explicit:
        return ResolvedKb(Path(explicit), "--kb override")
    here = Path.cwd()
    for candidate in (here, *here.parents):
        kb_dir = candidate / ".kb"
        if kb_dir.is_dir():
            return ResolvedKb(kb_dir, f"walked up from {here} to {kb_dir}")
    root = global_kb_root()
    return ResolvedKb(root, f"global fallback at {root}")


def _default_file_mode() -> int:
    """0666 narrowed by the process umask, matching what a plain
    `open()`/`Path.write_text()` would produce. `mkstemp` ignores umask
    and always makes its temp file 0600, so a file written through it
    needs this applied explicitly or it lands more restrictive than
    every other file this tool writes."""
    current_umask = os.umask(0)
    os.umask(current_umask)
    return 0o666 & ~current_umask


def _open_temp_file(directory: Path, prefix: str) -> tuple[int, Path]:
    """`mkstemp`, turning a read-only dir or a full disk into a clear
    exit instead of a bare traceback."""
    try:
        fd, tmp_name = tempfile.mkstemp(dir=directory, prefix=prefix)
    except OSError as exc:
        sys.exit(f"error: cannot write to {directory}: {exc}")
    return fd, Path(tmp_name)


def atomic_write_text(path: Path, content: str) -> None:
    """Write `content` to `path` without ever exposing a partially
    written file: build it in a same-directory temp file, then atomically
    replace. A crash mid-write leaves only the temp file behind, never a
    half-written `path`."""
    fd, tmp_path = _open_temp_file(path.parent, f".{path.name}.")
    try:
        os.fchmod(fd, _default_file_mode())
        with os.fdopen(fd, "w", encoding="utf-8", newline="") as handle:
            handle.write(content)
        os.replace(tmp_path, path)
    except OSError as exc:
        tmp_path.unlink(missing_ok=True)
        sys.exit(f"error: cannot write {path}: {exc}")
    except BaseException:
        tmp_path.unlink(missing_ok=True)
        raise


def write_source_file(sources_dir: Path, slug: str, content: str) -> Path:
    """Write a new, immutable source file. `sources/` never overwrites: on
    a slug race between parallel `add` calls, content is fully written to
    a temp file first, then exclusively hard-linked into place, so a
    losing process retries the next numbered suffix instead of clobbering
    the winner (closes the add/add TOCTOU on `path.exists()`)."""
    fd, tmp_path = _open_temp_file(sources_dir, f".{slug}.")
    try:
        os.fchmod(fd, _default_file_mode())
        with os.fdopen(fd, "w", encoding="utf-8", newline="") as handle:
            handle.write(content)
        suffix = 1
        while True:
            name = f"{slug}.md" if suffix == 1 else f"{slug}-{suffix}.md"
            candidate = sources_dir / name
            try:
                os.link(tmp_path, candidate)
            except FileExistsError:
                suffix += 1
                continue
            return candidate
    except OSError as exc:
        sys.exit(f"error: cannot write to {sources_dir}: {exc}")
    finally:
        tmp_path.unlink(missing_ok=True)


NO_STDIN_ERROR = "error: this command reads its body from stdin, but none was provided"

PAGE_STDIN_REQUIRED_ERROR = (
    "error: page requires a non-empty body from stdin (or pass --touch "
    "to re-stamp `updated` without touching the body)"
)

TOUCH_STDIN_ERROR = "error: --touch does not take a body; stdin held one"


def read_stdin_body() -> str:
    """Read a body from stdin, to EOF. No timeout, no "empty means keep
    the old body" heuristic: a body is required, so a caller with
    nothing to send is a caller bug (an inherited pipe that never
    closes), and it should hang visibly rather than have this function
    guess "empty" and silently discard whatever the caller was actually
    about to send. `--touch` on `page` is the only supported way to
    skip stdin.

    Exits loudly, never raises, when stdin is a tty (nothing was piped),
    already closed, or an fd closed out from under this process.
    """
    if sys.stdin is None or sys.stdin.closed or sys.stdin.isatty():
        sys.exit(NO_STDIN_ERROR)
    try:
        return sys.stdin.read()
    except (OSError, ValueError) as exc:
        sys.exit(f"error: failed to read stdin: {exc}")


def read_optional_stdin() -> str:
    """Read whatever is on stdin, if anything. No fd-type sniffing: a
    tty, `/dev/null`, a closed fd, a pipe, or a `< file` redirect of any
    size are all just read and judged by content, by `--touch` below."""
    try:
        return sys.stdin.read()
    except (OSError, ValueError):
        return ""


def generate_index(kb: Path) -> str:
    """Regenerate `wiki/index.md` content from page frontmatter only.

    Deterministic: pages sorted by filename, so two racing runs produce
    identical bytes.
    """
    wiki_dir = kb / "wiki"
    pages = sorted(
        (p for p in wiki_dir.rglob("*.md") if p.name != "index.md"),
        key=lambda p: p.name,
    )
    lines = [
        INDEX_BANNER,
        "",
        "| Page | Title | Summary | Category | Updated |",
        "|---|---|---|---|---|",
    ]
    for page in pages:
        fields, _ = parse_frontmatter(page.read_text(encoding="utf-8"))
        row = [page.stem] + [fields.get(name, "") for name in PAGE_FIELDS]
        cells = [cell.replace("|", "\\|") for cell in row]
        lines.append("| " + " | ".join(cells) + " |")
    return "\n".join(lines) + "\n"


def write_index(kb: Path) -> Path:
    """Regenerate `wiki/index.md` and return its path. The one place that
    writes the file, so `init`, `index`, `add` and `page` all stay in
    sync. No lock: two writers racing each regenerate from whatever they
    see on disk and the last `os.replace` wins, so the index can
    momentarily lag a page that just landed. That's fine, the index is
    derived and disposable; `llm-wiki index` recomputes it from what is
    actually on disk. The temp-file-plus-`os.replace` in
    `atomic_write_text` guarantees only that no reader ever sees a torn
    or half-written file, not that every writer's rows survive."""
    index_path = kb / "wiki" / "index.md"
    atomic_write_text(index_path, generate_index(kb))
    return index_path


def append_log_entry(kb: Path, kind: str, title: str) -> Path:
    """Append one `## [kind] title - timestamp` line to log.md and return
    its path. The one place that writes the file, so `log`, `add` and
    `page` all produce the same shape of entry. Raises `FileNotFoundError`
    if log.md is missing; the caller decides whether that is fatal."""
    log_path = kb / "log.md"
    if not log_path.is_file():
        raise FileNotFoundError(log_path)
    entry = f"## [{flatten(kind)}] {flatten(title)} - {utc_timestamp()}\n"
    with log_path.open("a", encoding="utf-8") as handle:
        handle.write(entry)
    return log_path


def append_log_entry_best_effort(kb: Path, kind: str, title: str) -> None:
    """Log a write `add`/`page` already made to disk. A missing log.md
    here is bookkeeping trouble, not a failed write: warn and exit 0."""
    try:
        append_log_entry(kb, kind, title)
    except FileNotFoundError as exc:
        print(f"warning: {exc} does not exist; log entry not recorded", file=sys.stderr)


class _NoAutoRedirect(urllib.request.HTTPRedirectHandler):
    """Turn a redirect into an HTTPError instead of silently following it,
    so every hop can be checked against the same scheme/host policy as
    the first."""

    def redirect_request(self, *args: object, **kwargs: object) -> None:
        return None


def _reject_unsafe_url(url: str) -> None:
    """Refuse anything but http(s) to an address that resolves as
    publicly routable right now, so `add --url` cannot be pointed at a
    local file or a loopback, link-local, or private address at check
    time. This is a point-in-time DNS check, not a connection-time one:
    it does not defend against DNS rebinding, where the name resolves
    differently between this check and the request that follows it."""
    parsed = urllib.parse.urlsplit(url)
    if parsed.scheme not in ALLOWED_URL_SCHEMES:
        sys.exit(f"error: fetching {url} failed: only http and https are allowed")
    if not parsed.hostname:
        sys.exit(f"error: fetching {url} failed: no host in URL")
    try:
        resolved = socket.getaddrinfo(parsed.hostname, None)
    except OSError as exc:
        sys.exit(f"error: fetching {url} failed: cannot resolve host: {exc}")
    for _family, _type, _proto, _canon, sockaddr in resolved:
        address = ipaddress.ip_address(sockaddr[0])
        if not address.is_global:
            sys.exit(f"error: fetching {url} failed: refuses a private or local address")


def _read_html(response: HTTPResponse, url: str) -> str:
    """Read and decode a response already checked against the URL policy,
    rejecting anything that is not html or too large to be a page."""
    content_type = response.headers.get_content_type()
    if content_type not in ALLOWED_CONTENT_TYPES:
        sys.exit(f"error: fetching {url} failed: content-type {content_type!r} is not html")
    raw = response.read(MAX_FETCH_BYTES + 1)
    if len(raw) > MAX_FETCH_BYTES:
        sys.exit(f"error: fetching {url} failed: response exceeds {MAX_FETCH_BYTES} bytes")
    charset = response.headers.get_content_charset() or "utf-8"
    return raw.decode(charset, errors="replace")


def fetch_url_text(url: str) -> tuple[str, str]:
    """Fetch `url` and return `(title, body_text)`.

    Only http(s) to a publicly routable address is allowed, and each
    redirect hop is re-checked against that policy. A network failure or
    a policy violation exits loudly before anything is written; there is
    no partial file to clean up either way. `lxml`/`readability-lxml`
    are imported only once a response is actually in hand, both so a
    rejected URL never needs them and so a missing install fails loudly
    here instead of with a raw traceback.
    """
    opener = urllib.request.build_opener(_NoAutoRedirect)
    current_url = url
    raw_html = ""
    for _ in range(MAX_REDIRECTS + 1):
        _reject_unsafe_url(current_url)
        request = urllib.request.Request(
            current_url, headers={"User-Agent": "llm-wiki/1.0"}
        )
        try:
            with opener.open(request, timeout=20) as response:
                raw_html = _read_html(response, current_url)
            break
        except urllib.error.HTTPError as exc:
            location = exc.headers.get("Location") if exc.headers else None
            if exc.code not in (301, 302, 303, 307, 308) or not location:
                sys.exit(f"error: fetching {current_url} failed: {exc}")
            current_url = urllib.parse.urljoin(current_url, location)
        except (urllib.error.URLError, TimeoutError, ValueError) as exc:
            sys.exit(f"error: fetching {current_url} failed: {exc}")
    else:
        sys.exit(f"error: fetching {url} failed: too many redirects")

    try:
        import lxml.html
        from readability import Document
    except ImportError as exc:
        sys.exit(
            "error: add --url needs readability-lxml and lxml: "
            f"pip install readability-lxml lxml ({exc})"
        )

    doc = Document(raw_html)
    title = doc.short_title() or url
    tree = lxml.html.fromstring(doc.summary())
    for tag in ("script", "style", "nav", "header", "footer"):
        for element in tree.xpath(f".//{tag}"):
            element.drop_tree()
    text = re.sub(r"\s+", " ", tree.text_content()).strip()
    return title, text


def require_dir(path: Path) -> None:
    """Guard clause: fail loudly if a kb verb is run before `init`."""
    if not path.is_dir():
        sys.exit(f"error: {path} does not exist; run `llm-wiki init` first")


def cmd_init(args: argparse.Namespace) -> None:
    if args.kb and args.path:
        sys.exit("error: give either a PATH or --kb, not both")
    if args.kb:
        target, reason = args.kb, "--kb"
    elif args.path:
        target, reason = args.path, "PATH argument"
    else:
        target, reason = "./.kb", "default ./.kb"
    kb = Path(target)
    kb.mkdir(parents=True, exist_ok=True)
    (kb / "sources").mkdir(exist_ok=True)
    (kb / "wiki").mkdir(exist_ok=True)
    schema_path = kb / "SCHEMA.md"
    if not schema_path.exists():
        schema_path.write_text(SCHEMA_TEMPLATE, encoding="utf-8")
    log_path = kb / "log.md"
    if not log_path.exists():
        log_path.write_text("", encoding="utf-8")
    write_index(kb)
    print(f"{kb.resolve()} (created via {reason})")


def cmd_where(args: argparse.Namespace) -> None:
    kb, how = resolve_kb(args.kb)
    resolved = kb.resolve()
    exists_note = "" if resolved.is_dir() else " (does not exist yet)"
    print(f"{resolved}{exists_note}")
    print(f"resolved via: {how}")


def cmd_add(args: argparse.Namespace) -> None:
    kb, _ = resolve_kb(args.kb)
    sources_dir = kb / "sources"
    require_dir(sources_dir)
    # --url never reads stdin at all: an inherited pipe that never closes
    # would otherwise hang every `--url` call waiting for input nobody is
    # going to send.
    if args.url:
        fetched_title, body = fetch_url_text(args.url)
        title = args.title or fetched_title
        source = args.url
    else:
        stdin_body = read_stdin_body()
        if not stdin_body.strip():
            sys.exit("error: add reads the body from stdin, or fetch one with --url")
        if not args.title:
            sys.exit("error: TITLE is required when adding from stdin")
        title = args.title
        body = stdin_body
        source = args.source or ""
    slug = slugify(title)
    fields = {
        "origin": args.origin,
        "source": source,
        "collected_at": utc_timestamp(),
    }
    content = render_frontmatter(fields) + f"\n# {title}\n\n{body}"
    path = write_source_file(sources_dir, slug, content)
    write_index(kb)
    append_log_entry_best_effort(kb, "ingest", title)
    print(path)


def cmd_page(args: argparse.Namespace) -> None:
    kb, _ = resolve_kb(args.kb)
    wiki_dir = kb / "wiki"
    require_dir(wiki_dir)
    slug = slugify(args.title)
    path = wiki_dir / f"{slug}.md"

    if path.exists():
        # newline="": default text-mode reading normalizes any \r\n or \r
        # in the body to \n, which would silently rewrite it on every
        # re-stamp. Read the exact bytes that are there instead.
        with path.open(encoding="utf-8", newline="") as handle:
            existing_text = handle.read()
        fields, existing_body = parse_frontmatter(existing_text)
        existing_title = fields.get("title", "")
        # No stored title (missing/unterminated frontmatter): adopt the
        # new one instead of demanding an impossible "pass back ''".
        if existing_title and _normalize_title_for_compare(
            existing_title
        ) != _normalize_title_for_compare(args.title):
            # Frontmatter title is ground truth for "is this the same
            # page"; a genuine difference landing on the same slug is a
            # collision, never a silent overwrite of someone else's body.
            sys.exit(
                f"error: slug {slug!r} already belongs to page titled "
                f"{existing_title!r}; {args.title!r} is not just a "
                f"case/whitespace/accent variant of it. To update that "
                f"page, pass its exact title back to `llm-wiki page`. To "
                f"write a new page, pick a title that slugifies "
                f"differently."
            )
    elif args.touch:
        sys.exit(f"error: --touch requires an existing page at {path}")
    else:
        fields, existing_body = {}, ""

    if args.touch:
        if read_optional_stdin().strip():
            sys.exit(TOUCH_STDIN_ERROR)
        body = existing_body
    else:
        body = read_stdin_body()
        if not body.strip():
            sys.exit(PAGE_STDIN_REQUIRED_ERROR)

    known_fields = {
        "title": args.title,
        "summary": args.summary if args.summary is not None else fields.get("summary", ""),
        "category": args.category if args.category is not None else fields.get("category", ""),
        "updated": utc_timestamp(),
    }
    extra_fields = {key: value for key, value in fields.items() if key not in PAGE_FIELDS}
    content = render_frontmatter({**known_fields, **extra_fields}) + "\n" + body
    atomic_write_text(path, content)
    write_index(kb)
    append_log_entry_best_effort(kb, "page", args.title)
    print(path)


def cmd_index(args: argparse.Namespace) -> None:
    kb, _ = resolve_kb(args.kb)
    require_dir(kb / "wiki")
    print(write_index(kb))


def cmd_log(args: argparse.Namespace) -> None:
    kb, _ = resolve_kb(args.kb)
    try:
        print(append_log_entry(kb, args.kind, args.title))
    except FileNotFoundError as exc:
        sys.exit(f"error: {exc} does not exist; run `llm-wiki init` first")


def cmd_links(args: argparse.Namespace) -> None:
    kb, _ = resolve_kb(args.kb)
    wiki_dir = kb / "wiki"
    require_dir(wiki_dir)
    page = args.page[:-3] if args.page.endswith(".md") else args.page
    pattern = f"[[{page}]]"
    if shutil.which("rg"):
        result = subprocess.run(
            [
                "rg", "-l", "--fixed-strings", "--no-ignore", "--hidden",
                pattern, str(wiki_dir),
            ],
            capture_output=True,
            text=True,
            check=False,
        )
        if result.returncode not in RG_OK_CODES:
            sys.exit(f"error: rg failed: {result.stderr.strip()}")
        hits = [line for line in result.stdout.splitlines() if line]
    else:
        hits = [
            str(path)
            for path in wiki_dir.rglob("*.md")
            if pattern in path.read_text(encoding="utf-8", errors="replace")
        ]
    for hit in sorted(hits):
        print(hit)


def build_parser() -> argparse.ArgumentParser:
    parent = argparse.ArgumentParser(add_help=False)
    parent.add_argument("--kb", default=None, help="kb path, overrides resolution")

    parser = argparse.ArgumentParser(prog="llm-wiki", description=__doc__)
    sub = parser.add_subparsers(dest="command", required=True)

    init_p = sub.add_parser("init", parents=[parent], help="create the kb tree")
    init_p.add_argument("path", nargs="?", default=None, help="default ./.kb")
    init_p.set_defaults(func=cmd_init)

    where_p = sub.add_parser("where", parents=[parent], help="print resolved kb")
    where_p.set_defaults(func=cmd_where)

    add_p = sub.add_parser("add", parents=[parent], help="write a source file")
    add_p.add_argument("title", nargs="?", default=None, help="required unless --url")
    add_p.add_argument(
        "--origin", choices=("curated", "research", "collector"), default="curated"
    )
    add_p.add_argument("--source", default=None)
    add_p.add_argument("--url", default=None, help="fetch and extract this URL, in place of stdin")
    add_p.set_defaults(func=cmd_add)

    page_p = sub.add_parser(
        "page", parents=[parent],
        help="write or update a wiki page, body from stdin, or --touch to re-stamp only",
    )
    page_p.add_argument("title")
    page_p.add_argument("--summary", default=None)
    page_p.add_argument("--category", default=None)
    page_p.add_argument(
        "--touch", action="store_true",
        help="re-stamp `updated` only, keep the body; refuses a non-empty stdin",
    )
    page_p.set_defaults(func=cmd_page)

    index_p = sub.add_parser(
        "index", parents=[parent],
        help="repair-only: regenerate wiki/index.md (add/page already do this)",
    )
    index_p.set_defaults(func=cmd_index)

    log_p = sub.add_parser(
        "log", parents=[parent],
        help="repair-only: append one entry to log.md (add/page already do this)",
    )
    log_p.add_argument("kind")
    log_p.add_argument("title")
    log_p.set_defaults(func=cmd_log)

    links_p = sub.add_parser("links", parents=[parent], help="pages linking to PAGE")
    links_p.add_argument("page")
    links_p.set_defaults(func=cmd_links)

    return parser


def main() -> None:
    parser = build_parser()
    args = parser.parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
